### ISSUE TITLE
Improve blog index page layout

### ISSUE THREAD

**Issue by MissyM2** [raft-tech/raft-tech.github.io#107]
Please comment here on any proposed changes to the layout, look and feel of the blog page here.

- reduce the number of characters used in the short_title so that wrapping does not occur.
- create some media queries for better layout on mobile devices
- decide on some categorization for blogs
- On mobile, consider blog index page that shows a listing of short_titles or categories, rather than the whole summary so a user doesn't have to scroll through all the articles.

I am just starting a list here for discussion.

![Screen Shot 2020-04-23 at 6 58 34 PM](https://user-images.githubusercontent.com/34319929/80157797-f75de000-8594-11ea-90e1-917208330df9.png)

![Screen Shot 2020-04-23 at 7 03 07 PM](https://user-images.githubusercontent.com/34319929/80157852-178d9f00-8595-11ea-877a-2ca1d95d7771.png)
@meissadia @RedNumberIX @Omnipresent

**Comment by BarakStout** [comment]
I think a simple, short term approach would be to reduce the font sizes and padding Something like this might work.

<img width="399" alt="Screen Shot 2020-04-23 at 9 55 41 PM" src="https://user-images.githubusercontent.com/34528865/80166980-457edd80-85ad-11ea-89a4-394008083a5a.png">
