### ISSUE TITLE
Fix blog posts file names 

### ISSUE THREAD

**Issue by BarakStout** [raft-tech/raft-tech.github.io#156]
![Screen Shot 2020-07-13 at 10 44 48 AM](https://user-images.githubusercontent.com/34528865/87318122-e7033480-c4f5-11ea-9573-4ab0e1582498.png)

**Comment by meissadia** [comment]
@BarakStout "Fix" and in "standardize"? 

Seems like we would need to coordinate this with our social media folks since we could break links that have already been posted.
