### ISSUE TITLE
Previously suggested edits to goraft.tech sections for cross-checking

### ISSUE THREAD

**Issue by bb-at-raft** [raft-tech/raft-tech.github.io#157]

**Comment by bb-at-raft** [comment]
Dated Jan 2020, but might be helpful to cross-check, as "close paren vs. hyphen" typo was referenced below:

On Tue, Jan 21, 2020, at 11:21 PM, Beata Barci wrote:

Our Work: 
- [ ] Challenge -- capitalize K in 15K 
- [ ] Solution -- 
sentence 1: make "level" plural;  
sentence 3: change "provided" to providing; should acronyms be spelled out? 
sentence 4: cassandra not capitalized here but is below;  
- [ ] Techniques -- typo PostgreSQL 

DevSecOps: 
- [ ] Challenge -- for parallel structure, should order be development, security, then operations 
- [ ] Solution -- second to last sentence typo:  "deployin"  

Data Science: 
- [ ] Challenge -- sentence 2 typo:  missing should "be" detected 

Product Strategy: 
- [ ] Solution:  sentence 1:  add "a" after Following; sentence 2: analysing is typically British English spelling vs. analyzing  
- [ ] Techniques:  perhaps choose either title case or sentence case, rather than both 

Join: 
- [ ] Consider changing atypical contraction "Who're" (read quickly looks like whore ;P back to "Who are"  
- [ ] Our Interview process -- capital i or p? 
- [ ] Bullet one typo -- with one OF (missing) our engineers 
- [ ] Bullet two typo -- positive missing i; work on A (missing) problem 

Contact: 
- [ ] Phone number format:  571-526-4106 or (571) 526-4106 
- [ ] In footer, "Suite" is not used 
- [ ] Should email address be hyperlink? 

Services - Cloud Native: 
- [ ] How we do Cloud Native:  delete one of two "scalable scalable" 
- [ ] Scalability -- typo application 
- [ ] DDD -- typo By not Bu 
- [ ] Our Expertise -- any particular reason for the order (priorities, level of expertise, process, alpha?) 
- [ ] Microservices -- fulfill (British English), fulfill (American English); Prometheus capitalized on other pages 
- [ ] Air gapped environments -- capitalize G and E or not? 
- [ ] IaC -- typos:  "If" is capitalized, isn't and doesn't are missing apostrophes 

Data Science: 
- [ ] Detect Bias: should it be "Bias Detection" (noun) for parallel structure?  modelling (British English) vs. modeling 
- [ ] Prototype & Iterate:  typo Minimum instead of Minimal Viable Product 
- [ ] Data Pipelines:  here "open source" was hyphenated? 
- [ ] Machine Learning:  sentence 2:  typo "amounts" plural instead of singular 

DevSecOps: 
- [ ] Developer Focused:  "Developers" capitalized or not?  Afterthought is one word, not hyphenated 
- [ ] Pipeline Driven:  "that'd" not a common contraction 
- [ ] Continuous Monitoring:  sentence 1: idiom is "be-all and end-all"; sentence 2: change "going" to "go" 
- [ ] Immutable:  teams is possessive and needs apostrophe 
- [ ] Our Expertise - Kubernetes: delete common between sentences 1 and 2; sentence 2: should be "its" (no apostrophe) 

Product Strategy: 
- [ ] "Creating...audiences" -- title case or sentence case?  Sentence case was used with other Services' headers (and no period) 
- [ ] Typo or omit question mark?  "How [do] we do Product strategy" 
- [ ] Buckets are verbs except "Execution" -- need parallel structure here or with other pages? 
- [ ] Define Success:  sentences 2 & 3: criteria = plural so use "are" and "measure" as verbs; delete one "s" from focusses 
- [ ] Development:  last sentence:  perhaps modify to read:  "We are proponents of open source and resist vendor lock-in." 


On Tue, Jan 21, 2020, at 9:29 PM, Beata Barci wrote: 

Homepage: 
- Nice sized raft logo :) 
- [ ] Is permission needed to use GitHub symbol, etc.? 
- [ ] 2nd and 4th figures don't have eyes like others do? 
- [ ] Maybe make hand holding cloud umbrella more similar to shape of figure 4? 

About: 
- [ ] Why Should I go Raft? -- should "go" be uppercase as well; will "Raft" be uppercase throughout and just lowercase as logo? 
- [ ] ...vendor lock in -- shouldn't lock-in be hyphenated? 
- [ ] maybe omit the dig on bankers' dressing -- even banks are adding coffee bars to draw people in ;) 
- [ ] Our Experience -- "open source" not capitalized here, but capitalized in section above 
- [ ] Buzzwords is one word 
- [ ] Typo -- Prime not Pime contractors 
- [ ] Instead of using "DoD" maybe use federal or government, and make "Civilian" lowercase? 
- [ ] Isn't C2S = Commercial Cloud Services not Solutions 
- [ ] Apache Kafka uses registered trademark symbol (https://kafka.apache.org/intro) -- should this be checked for all?  Need comma before etc. 
- [ ] Product Development typo -- missing space between "data in" 
- [ ] - First two bullet points missing periods at end or perhaps delete periods from those below 
- [ ] - Our Leadership -- after IDIQs need comma not period; need "a" before "decade's" 
- [ ] - Zip code missing after Texas; phone/fax numbers the same?  better to choose format:  (571) 526-4106 or 571-526-4106

**Comment by meissadia** [comment]
## Remaining Items

Services - Cloud Native: 
- [ ] Our Expertise -- any particular reason for the order (priorities, level of expertise, process, alpha?) 

Homepage: 
- [x] Is permission needed to use GitHub symbol, etc.? 
  - Safe to use logo to link to github: https://github.com/logos
- [ ] 2nd and 4th figures don't have eyes like others do? 
- [ ] Maybe make hand holding cloud umbrella more similar to shape of figure 4? 

About: 
- [ ] Why Should I go Raft? -- should "go" be uppercase as well; will "Raft" be uppercase throughout and just lowercase as logo?  
  - if "raft" officially lower case?
- [ ] Apache Kafka uses registered trademark symbol (https://kafka.apache.org/intro) -- should this be checked for all?  
  - I don't see a Kafka logo anywhere, will double check.

**Comment by meissadia** [comment]
New tickets spawned to addressed outstanding issues.  

Closing this.
