### ISSUE TITLE
Home page graphical suggestions

### ISSUE THREAD

**Issue by BarakStout** [raft-tech/raft-tech.github.io#170]
Forward from #157 

[Referenced image](https://goraft.tech/assets/header_image_big.jpg)
- [ ] Should 2nd and 4th figures have eyes like the others do?
- [ ] Maybe make hand holding cloud umbrella more similar to shape of figure 4?

**Comment by Mike-Mancuso** [comment]
I don't really think that the characters in the art itself need eyes.
