### ISSUE TITLE
Move the text on the hero images of the blog

### ISSUE THREAD

**Issue by raft-cso** [raft-tech/raft-tech.github.io#173]
We need to align all the text on the hero image to the left (title + "written by x" + date + twitter / linkedin logos. 

Please see attached image for a rough example. 

The font might need be made a bit smaller as well.

![example](https://user-images.githubusercontent.com/63659579/88699419-4dcb4500-d0d5-11ea-95cc-ea989bfeed6c.PNG)

**Comment by meissadia** [comment]
@raft-cso I've added a few options to make the blog post headers more configurable.  I've also added a darkened tint overlaying the header background image (which we can also make configurable) in an attempt to improve the readability of the header text and the site navigation text.

By default, headers will now be aligned to the left on larger screens but will always show centered and full-width on smaller screens. 

<img width="1624" alt="large-screen-left" src="https://user-images.githubusercontent.com/2592907/89113249-c3177c80-d42b-11ea-807a-5196f6c7732e.png">
<img width="810" alt="small-screen-full" src="https://user-images.githubusercontent.com/2592907/89113251-c4e14000-d42b-11ea-9c0c-3ac55a4164a9.png">

## Options
The two options I've added are `headerAlign` and `headerBackground`, which can be used in the yaml for each blog post. 
<img width="715" alt="options" src="https://user-images.githubusercontent.com/2592907/89113378-9f553600-d42d-11ea-9ce0-52b7bc97a0c3.png">

`headerAlign` can be one of the following: `center, right`.  Again, headers are aligned left be default, so no `headerAlign` entry is needed for that scenario.

`headerBackground` can be set to `true` if we want to add a background to the header text to improve readability against the background image, or omitted when not needed.

## Examples:

- Header left, no text background: https://raft-website.herokuapp.com/2020/07/13/content-style-guide.html
- Header left, with text background: https://raft-website.herokuapp.com/2020/05/20/hcd.html
- Header center, with text background: https://raft-website.herokuapp.com/2020/06/22/Host-a-Morale-Boosting-Virtual-Happy-Hour.html
- Header center, no text background: https://raft-website.herokuapp.com/2020/02/19/engineering-principles.html

I've avoided using the `headerAlign: right` option thus far and instead opted to adjust images where necessary.
i.e. [Before](https://goraft.tech/2020/03/25/remote-work.html) => [After](https://raft-website.herokuapp.com/2020/03/25/remote-work.html)
## Outcome
This leads to a less consistent layout of blog posts but also avoids having to go through and update all of the header background images, though that's always an option.

Let me know what you think.  Happy to discuss these changes and the potential addition of any other layout options that you think would help improve the site.

**Comment by meissadia** [comment]
@raft-cso Sorry, Barak had some good feedback so I've made adjustments.  The above comment no longer relevant. 

- Fixed text alignment (if `headerAlign: left`, all text is aligned left.  Same with `center` or `right`)
- No longer adding a background color to header text, instead allowing a gradient tint to be applied over the header image for better text visibility. This can be controlled for each post: 
  ```
  headerOverlay: none|left|right|all
  headerAlign: left|center|right
  ```

Example: [Gradient overlay](https://raft-website.herokuapp.com/2020/05/20/hcd.html)
```
headerOverlay: left
headerAlign: left
```

Gradient will be applied on larger screens 
<img width="1624" alt="headerOverlay-left-large" src="https://user-images.githubusercontent.com/2592907/89115265-a25b2100-d443-11ea-82e3-b9ee4594f82d.png">

Solid overlay always applied on smaller screen. Text always centered on smaller screens.
<img width="819" alt="headerOverlay-left-small" src="https://user-images.githubusercontent.com/2592907/89115268-a9822f00-d443-11ea-9a60-b5e6d483558d.png">

Example: [No overlay](https://raft-website.herokuapp.com/2020/07/13/content-style-guide.html)
```
headerOverlay: none
headerAlign: left
```

No overlay will be applied on larger screens
<img width="1645" alt="Screen Shot 2020-08-01 at 10 14 13 PM" src="https://user-images.githubusercontent.com/2592907/89115325-7ab88880-d444-11ea-9381-44f534baf2ea.png">

Solid overlay always applied on smaller screen. Text always centered on smaller screens.
<img width="810" alt="Screen Shot 2020-08-01 at 10 14 20 PM" src="https://user-images.githubusercontent.com/2592907/89115335-86a44a80-d444-11ea-83ea-bbea8647b39c.png">


Example: [Solid overlay](https://raft-website.herokuapp.com/2020/06/22/Host-a-Morale-Boosting-Virtual-Happy-Hour.html)
```
headerOverlay: all
headerAlign: center
```
