### ISSUE TITLE
Add new members

### ISSUE THREAD

**Issue by omnipresent07** [raft-tech/raft-tech.github.io#226]
- Ethan
- Angela
- John
- Arthur
- Kati
- Le Chen

**Comment by MissyM2** [comment]
got it.  I'll do it tomorrow. @omnipresent07

**Comment by MissyM2** [comment]
Added Le Chen in PR #220
Kati and Angela are being added in PR #231 
Ethan, John and Arthur will be added when they start.  Issue number is #232 (bios) and #233 (images)

fyi @omnipresent07
