### ISSUE TITLE
Map on teams  or about page that shows every where Rafters are

### ISSUE THREAD

**Issue by omnipresent07** [raft-tech/raft-tech.github.io#234]
some kind of cool map on our website that shows where all rafters are from. maybe a tooltip on each point in the map that shows the rafters or takes back to their profile page?

[non-urgent]. Suppose to be a fun thing.

**Comment by BarakStout** [comment]
@omnipresent07 duplicate with #199

**Comment by omnipresent07** [comment]
closing this . tagged @meissadia on that one.
