### ISSUE TITLE
DAGOBAH - Product Blog

### ISSUE THREAD

**Issue by omnipresent07** [raft-tech/raft-tech.github.io#271]
What is DAGOBAH - Define problem statement, define our approach, define progress we've made so far, define working with airmen coders. How we managed the fast paced project. 

Outline (Just section titles) due date: End of April, 2021
Final Draft Due Date: May 2nd week

**Comment by amilash** [comment]
What format would you like this in? What audience is it for?

**Comment by omnipresent07** [comment]
> What format would you like this in? What audience is it for?

This doc should have doc info on format: https://github.com/raft-tech/raft-tech.github.io#creating-a-blog-post-non-devs

Audience - Similar audience to https://goraft.tech/blog/ . Please feel free to MM if you have more Q's. This repo is public.

**Comment by amilash** [comment]
@omnipresent07 see issue: **https://github.com/raft-tech/raft-tech.github.io/issues/301** for post submission.'ve tagged Barak and Marc for review submission as the repo indicates.
