### ISSUE TITLE
Add biographies to leadership page

### ISSUE THREAD

**Issue by victoriaatraft** [raft-tech/raft-tech.github.io#441]
**Links/Deliverables:**

- ### [View all the bios here](https://gorafttech-my.sharepoint.com/:w:/g/personal/vamoroso_teamraft_com/EecuhmTm-o9IqhNif7WYEFYBSxgdZTAfWwVpIXTI_H5RUg?e=LTBD00)
- [Link to figma design page here](https://www.figma.com/file/SMkkMTzoskcNJit5OhYYIk/The-Raft-Website-Design?type=design&node-id=990-142239)

**Note:**
- Their hover picture shows on click

**Would be nice:**
- on click the add button animates to close something similar to this https://lottiefiles.com/63953-add-button

**Comment by victoriaatraft** [comment]
<img width="879" alt="Screenshot 2023-07-25 at 7 22 21 AM" src="https://github.com/raft-tech/raft-tech.github.io/assets/106103383/dd50d620-6951-4674-9c84-91c70b921a2d">

**Comment by victoriaatraft** [comment]
**Reston, Virginia**
- Shubhi
- Bhaarat
- Tami
- Jake
- Danielle

Angie: 
**Lorton, Virginia**

Sam:
**St. Petersburg, Florida**

Kristen
**Colorado Springs, Colorado**

Jess
**Columbus, Ohio**

Steve
**Whitesboro, New York**

Jesse
**Gainesville, Virginia**

Dagan
**Rocklin, California**

**Comment by desidia26** [comment]
Addressed and pushed to staging!
