### ISSUE TITLE
Increase Spacing and Display Sub Headers on Mobile Navigation Menu

### ISSUE THREAD

**Issue by victoriaatraft** [raft-tech/raft-tech.github.io#444]
**Deliverables/Links:**
### [Link to the Figma File Page for the Mobile Navigation](https://www.figma.com/file/VNcqkBzyw7opz1ouGSCHqC/The-Raft-Website-Development?type=design&node-id=990-137862)

**Notes:**
- The sub text displays since there is no hover
- Please remove "and Innovation Toolkit" from focus areas on narrow and wide screen navigations
- 2rem for the navigation header (32px) on mobile for the navigation
- 0.875rem for the sub text under the nav menu
- please align the content underneath to align with R in Raft logo 
- 32px between each navigation menu item

<img width="736" alt="Screenshot 2023-06-12 at 2 36 18 PM" src="https://github.com/raft-tech/raft-tech.github.io/assets/106103383/0ece0b24-3c77-4bd6-bd83-21957cb6195d">

**Comment by benmarte** [comment]
Since the navigation is built dynamically I can't control only showing "and innovation toolkit" so either we keep it or we remove it.

Let me know how you want to proceed with this specific nav item.

**Comment by victoriaatraft** [comment]
Hi. Let's remove "and innovation toolkit" completely. We don't have a page or section built for that :)

**Comment by victoriaatraft** [comment]
- [ ] Text default color should be #E3E3E3 ie "we are nerdy humans"
- [ ] subtext should display all the time only on mobile
- [ ] logo needs to be more aligned with the navigation items
- [ ] sub text should be in Space Mono

**Comment by desidia26** [comment]
Addressed and deployed!
