### ISSUE TITLE
Animate text: Together, Let's Make Waves in the footer

### ISSUE THREAD

**Issue by victoriaatraft** [raft-tech/raft-tech.github.io#456]
It would be nice if we can do this. If it doesn't bloat the site 😅

[Here's the link for inspiration](https://www.phimher.com/coaching). 
It's a squarespace thing

**The text styling is** 
Space Mono 
Bold 
All Uppercase
8% letter spacing

**Comment by victoriaatraft** [comment]
- Font should be in Space Mono 500 or 600
- Text should be FAFAFA on dark mode
- Text should be default 474747 on light

**Comment by desidia26** [comment]
> * Font should be in Space Mono 500 or 600
> * Text should be FAFAFA on dark mode
> * Text should be default 474747 on light

Addressed and deployed!
