### ISSUE TITLE
Update footer text above "Join Team Raft" button in the footer

### ISSUE THREAD

**Issue by victoriaatraft** [raft-tech/raft-tech.github.io#459]
in the footer above the button "Join Team Raft" 
please update the text from: "Come be part of the mission. We are a team of 150+ awesome humans and growing"to 

Come be part of the mission. We are a team of **200+** awesome humans and growing.

**Comment by benmarte** [comment]
We should probably rethink having the number of employees because this is going to be something that's going to keep changing and it's going to be hard to keep updated with the actual count.
