### ISSUE TITLE
Meta tags on blog posts

### ISSUE THREAD

**Issue by omnipresent07** [raft-tech/raft-tech.github.io#46]
In `head.html` we currently have a `meta` section for `<!-- Twitter: card tags -->`. Currently these are defaulted to raft logo. We'd like these to match the thumbnail images that are specified via `featimg` label in the posts. 

I tried using `cover`, however, that adds the image to the background of the post. Rather we need to use a specific label (similar to `featimg`) for each post that maps to `site.protocols.twitter_image`

**Comment by omnipresent07** [comment]
@RedNumberIX Via this pull request by @BarakStout the cards on twitter should work. See image below

<img width="1032" alt="Screen Shot 2020-02-11 at 11 17 55 AM" src="https://user-images.githubusercontent.com/44377678/74256139-e9e8c780-4cc0-11ea-94f6-f7a602c0f3da.png">

**Comment by RedNumberIX** [comment]
Great! The image doesn't look too bad. 
The next priority on the card validator would be editing the copy inside of the Card Validator. Right now it just pulls the first line of body text, but it'd be much better if I could put in a custom summary.

**Comment by omnipresent07** [comment]
Lets create a separate ticket for that. That issue should not be urgent though and shouldn't be a blocker for us to start pushing content.
