### ISSUE TITLE
Add preview of Case Studies under Focus Areas

### ISSUE THREAD

**Issue by victoriaatraft** [raft-tech/raft-tech.github.io#460]
Similar to the Blog. 
There will be a dedicated case studies page when the user selects "view all cases"
[Link to the figma page ](https://www.figma.com/file/SMkkMTzoskcNJit5OhYYIk/The-Raft-Website-Design?type=design&node-id=990-167517)

**Comment by victoriaatraft** [comment]
- Text should be left aligned
- Sub header title above "focus area"
- boarder radius of 2 - 4px

**Comment by desidia26** [comment]
> * Text should be left aligned
> * Sub header title above "focus area"
> * boarder radius of 2 - 4px

Addressed and deployed!
