### ISSUE TITLE
Update Danielle McCoy's Bio from 15 years to 10 years

### ISSUE THREAD

**Issue by victoriaatraft** [raft-tech/raft-tech.github.io#466]
Please change 15 years to **10 years.** 
Location: Raft About Page 

Senior Director of People Danielle has built, scaled, and transformed award-winning companies known for their people-first cultures for over 15 years.... 

<img width="1628" alt="Screenshot 2023-08-11 at 8 53 52 AM" src="https://github.com/raft-tech/raft-tech.github.io/assets/106103383/b8576925-0d7e-45bd-87d2-be4cd64743b8">

**Comment by BarakStout** [comment]
@desidia26 is this closed by a PR ?

**Comment by desidia26** [comment]
> @desidia26 is this closed by a PR ?

It is now. Thanks for the comment, I didn't get notifications for new tickets, but will now make sure that I do.

**Comment by BarakStout** [comment]
PR Merged
