### ISSUE TITLE
Create a blog post on our remote first culture

### ISSUE THREAD

**Issue by omnipresent07** [raft-tech/raft-tech.github.io#64]
Create a blog post on remote culture

**Comment by meissadia** [comment]
@omnipresent07 Fixed by https://github.com/raft-tech/raft-tech.github.io/pull/77 or is this a different idea?

**Comment by RedNumberIX** [comment]
With the blog post now live I'll go ahead and close this ticket.
[https://goraft.tech/2020/03/25/remote-work.html](https://goraft.tech/2020/03/25/remote-work.html)
