### ISSUE TITLE
Add authors to existing blog posts

### ISSUE THREAD

**Issue by omnipresent07** [raft-tech/raft-tech.github.io#66]
Now that we have ability to add author names to blog posts (via https://github.com/raft-tech/raft-tech.github.io/pull/61) , lets add the author names to existing blog posts

**Comment by meissadia** [comment]
@PatrickGoRaft @BarakStout @omnipresent07 Please add/correct any post authors that you know.  I can follow up on MM to fill in any subsequent gaps.

| Title | Author |
|---|---|
| Emerging Mobile UI and Web Design Trends of 2020 | Shubhi Mishra |
| Why Progressive Web Apps are the future of Mobile Development | Shubhi Mishra |
| Raft Engineering Principles | Bhaarat Sharma |
| Human Centered Design | ? |
| Python for Machine Learning | ? |
| Neural Networks | ? |
| Intro to HPC | ? |
| Dimensionality Reduction | ? |
| CNN Object Detection |  ? |

**Comment by BarakStout** [comment]
@meissadia can this be closed?

**Comment by meissadia** [comment]
👍 Fixed by #87
