### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by BarakStout** [raft-tech/raft-tech.github.io#86]
Now that the site is up, we should update the readme from the temples one. We should include instructions on how to run locally, create post, etc.

**Comment by meissadia** [comment]
I'll be working with @RedNumberIX next week to get up and running locally.  We'll document the processes.

**Comment by meissadia** [comment]
Raft Website - Local Installation (1st draft)
https://hackmd.io/iNjpkZhQTM62Iws8Y4wcjw

**Comment by BarakStout** [comment]
@meissadia Readme has been updated. This can be closed.
