### ISSUE TITLE
Update site description 

### ISSUE THREAD

**Issue by BarakStout** [raft-tech/raft-tech.github.io#91]
We should update the site title and description so our site looks better in search results. 

<img width="857" alt="Screen Shot 2020-04-03 at 8 15 46 AM" src="https://user-images.githubusercontent.com/34528865/78359651-7b6b0c00-7583-11ea-8ed3-6f2e1a708db6.png">

**Comment by RedNumberIX** [comment]
Hey Barak! Yeah, these are controlled by the metadata description and title tags I mentioned in a past marketing meeting. I wrote the copy for the featured pages for Shubhi and @Omnipresent  to approve. 

[Like to GoRaft.Tech MetaData Descriptions Document](https://gorafttech-my.sharepoint.com/:w:/g/personal/rhunter_goraft_tech/EcT_RH-G0xJIvVjGLa1_p8oBSFq5nCweQN2JtoUr6lbyJg?e=mx4uxp)

**FYI:** Titles are 72 chars Max, Description are 172 chars Max, (the secondary pages will cut descriptions off at 60 characters). For those interested, [click here](https://seopressor.com/blog/google-title-meta-descriptions-length/) to learn more about MetaData Descriptions and my methodology for writing these.

**Comment by meissadia** [comment]
@RedNumberIX did you ever get confirmation on the updated page descriptions?
